---
title: "Publications"
author: "EE"
date: "1/14/2020"
output: html_document
---

You can also check out my profiles on [Google Scholar](https://scholar.google.com/citations?user=d3WGzzkAAAAJ&hl=en) and [Researchgate](https://www.researchgate.net/profile/Eric_Ekholm)

#### Peer-Reviewed Publications

+ Gellock, J., __Ekholm, E.__, Greenhalgh, G., LeCrom, C., Reina, C., & Kudesia, R. (2019). Women’s lacrosse players’ perceptions of teammate leadership: Examining athlete leadership behaviors, attributes, and interactions. _Journal of Athlete Development and Experience, 1(2)_, 2. https://scholarworks.bgsu.edu/jade/vol1/iss2/2.  

+ Zumbrunn, S., Marrs, S., Broda, M., __Ekholm, E.__, Jackson, L., & DeBusk-Lane, M. (2019). Toward a more complete understanding of writing enjoyment: A mixed methods study of elementary students. _AERA Open, 5(2)_, https://doi.org/10.1177/2332858419850792.

+ Broda, M., Tucker, S., __Ekholm, E.__, Johnson, T., & Liang, Q. (2019).  Small fingers, big data: Preschoolers’ subitizing speed and accuracy during interactions with multi-touch technology.  _The Journal of Educational Research, 112(2)_, 211-222. https://doi.org/10.1080/00220671.2018.1486281.

+ __Ekholm, E.__ & Chow. J. C. (2018). Addressing publication bias in educational psychology. _Translational Issues in Psychological Science, 4(4)_, 425-439. http://dx.doi.org/10.1037/tps0000181.

+ Broda, M., __Ekholm, E.__, Schneider, B., & Hutton, A. (2018). Teachers’ social networks, college-going practices, and the diffusion of a school-based reform initiative. _SAGE Open_. https://doi.org/10.1177/2158244018817397.

+ Chow, J.C., __Ekholm, E.__, & Coleman, H. (2018). Does oral language underpin the development of later behavior problems? A longitudinal meta-analysis. _School Psychology Quarterly, 33(3)_, 337-349. http://dx.doi.org/10.1037/spq0000255.

+ Chow, J.C., & __Ekholm, E.__ (2018). Do published studies yield larger effect sizes than unpublished studies in education and special education? A meta-review. _Educational Psychology Review, 30(3)_, 727-744. https://doi.org/10.1007/s10648-018-9437-7.

+ Chow, J. C., & __Ekholm, E.__ (2018). Language domains differentially predict mathematics performance in young children.  _Early Childhood Research Quarterly, 46_, 179-186. https://doi.org/10.1016/j.ecresq.2018.02.011

+ __Ekholm, E.__, Zumbrunn, S. & DeBusk-Lane, M. (2018). Clarifying an elusive construct: A systematic review of writing attitudes. _Educational Psychology Review, 30(3)_, 827-856. https://doi.org/10.1007/s10648-017-9423-5.

+ __Ekholm, E.__ (2017). Ethical concerns of using texts involving death in the English classroom. _English Journal, 107(2)_, 25-30.

+ Zumbrunn, S., __Ekholm, E.__, Stringer, J. K., McKnight, K., & DeBusk-Lane, M. (2017). Student experiences with writing: Taking the temperature of the classroom. _The Reading Teacher, 70(6)_, 667-677. https://doi.org/10.1002/trtr.1574.

+ __Ekholm, E.__, Zumbrunn, S., & Conklin, S. (2015). The relation of college student self-efficacy toward writing and writing self-regulation aptitude: writing feedback perceptions as a mediating variable. _Teaching in Higher Education, 20(2)_, 197-207. https://doi.org/10.1080/13562517.2014.974026.

<br/>

#### Other Publications

##### Fiction and Humor

+ __Ekholm, E__. [“If You Take My Survey, I’ll Let You Watch Me Cut My Finger Off.”](https://www.mcsweeneys.net/articles/if-you-take-my-survey-ill-let-you-watch-me-cut-my-finger-off) McSweeney’s Internet Tendency (June 7, 2016).

+ __Ekholm, E.__ [“Call for Submissions for APA’s Annual Conference, Sponsored by Shark Week.”](http://www.mcsweeneys.net/articles/call-for-submissions-for-apas-annual-conference-sponsored-by-shark-week)  McSweeney’s Internet Tendency (August 11, 2014).  

##### Book Reviews

+ __Ekholm, E.__ (September, 2016).  [A review of Kelly Gallagher’s _In the Best Interests of Students_.](http://www.ncte.org/library/NCTEFiles/Resources/Journals/EJ/1061_sep2016/EJ1061Reviews.pdf)

##### Other

+ Guest blog post, AERA Motivation SIG Blog, __Ekholm, E.__ (2018). [“What Motivation Researchers Can Learn from Professional Sports Teams.”](http://motsig.org/what-motivation-researchers-can-learn-from-professional-sports-teams/) November 6, 2018. 

<br/>

#### Conference Presentations
_*Only conference presentations since 2017 included_
